### ISSUE TITLE
globalize your isAuthenticated middleware

### ISSUE THREAD

**Issue by nakaz** [aukai84/express-gallery#3]
notice how you're repeating yourself in every route with calling the `isAuthenticated` as middleware in each of them? 

You can totally use your `isAuthenticated` as a app-level middleware instead -- only on routes that requests with `POST`, `PUT`, and `DELETE` methods. If requests of any of those methods you can have it go through the `isAuthenticated` middleware before finally reaching the designated route.

**Comment by aukai84** [comment]
fixed issue
